all:

  hosts:

    vm-asterix-fim-01:
      ansible_host: host1_ip / domain
      ansible_user: debian

    vm-asterix-fim-02:
      ansible_host: host2_ip / domain
      ansible_user: debian

  children:

    asterix-servers:

      hosts:

        vm-asterix-fim-01: ~
        
    asterix-dbservers:

      hosts:
      
        vm-asterix-fim-02: ~


    
